- type: http
  id: external_confluent_control_center_endpoint
  name: Confluent Control Center External
  hosts: ["http://${MODECO_HOSTNAME}:${MODECO_KAFKA_CONNECT_ENDPOINT_PORT}"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: confluent_cc
    type: external
    service: control_center
    area: endpoint




- type: http
  id: internal_confluent_control_center_endpoint
  name: Confluent Control Center Internal
  hosts: ["http://${MODECO_MODULEPREFIX}_confluent_control_center:9021"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: confluent_cc
    type: internal
    service: control_center
    area: endpoint
