- type: http
  id: external_kafka_rest_endpoint
  name: Kafka REST External
  hosts: ["http://${MODECO_HOSTNAME}:${MODECO_KSQL_KSQL_SERVER_ENDPOINT_PORT}"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: kafka_rest
    type: external
    service: kafka_rest
    area: endpoint




#- type: http
#  id: internal_kafka_rest_endpoint
#  name: Kafka REST Internal
#  hosts: ["http://${MODECO_MODULEPREFIX}_kafka_rest_kafka_rest:8082"]
#  check.response.status: [200]
#  schedule: '@every 30s'
#  fields:
#    scope: "${MODECO_STACKSCOPE}"
#    stack: kafka_rest
#    type: internal
#    service: kafka_rest
#    area: endpoint
