- type: http
  id: external_kafka_connect_endpoint
  name: Kafka Connect External
  hosts: ["http://${MODECO_HOSTNAME}:${MODECO_KAFKA_CONNECT_ENDPOINT_PORT}"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: kafka_connect
    type: external
    service: kafka_connect
    area: endpoint




- type: http
  id: internal_kafka_connect_endpoint
  name: Kafka Connect Internal
  hosts: ["http://${MODECO_MODULEPREFIX}_kafka_rest_kafka_rest:8083"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: kafka_connect
    type: internal
    service: kafka_connect
    area: endpoint
