- type: http
  id: external_ksql_ksql_server_endpoint
  name: KSQL Server External
  hosts: ["http://${MODECO_HOSTNAME}:${MODECO_KSQL_KSQL_SERVER_ENDPOINT_PORT}"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: ksql
    type: external
    service: ksql_server
    area: endpoint




- type: http
  id: internal_ksql_ksql_server_endpoint
  name: KSQL Server Internal
  hosts: ["http://${MODECO_MODULEPREFIX}_ksql_ksql_server:8088"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: ksql
    type: internal
    service: ksql_server
    area: endpoint
