- type: http
  id: external_processor_streamsets_endpoint
  name: Processor StreamSets External
  hosts: ["http://${MODECO_HOSTNAME}/${MODECO_URLPREFIX}/processor/streamsets"]
  check.response.status: [301]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: streamsets
    type: external
    service: streamsets
    area: endpoint




- type: http
  id: internal_processor_streamsets_endpoint
  name: Processor StreamSets Internal
  hosts: ["http://${MODECO_MODULEPREFIX}_processor_streamsets:18630"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: "${MODECO_STACKSCOPE}"
    stack: streamsets
    type: internal
    service: streamsets
    area: endpoint
