---
version: '3'
services:

# START SERVICE registry.base
  registry:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.registry.base:2
    environment: []
    command: []
    volumes: [${CONTECO_STACKPREFIX}_registry_volume:/var/lib/registry]
    ports: [${REGISTRY_PORTS}]
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${REGISTRY_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${REGISTRY_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${REGISTRY_COMPOSE_EXTENSIONS}
# END SERVICE registry.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_registry_volume: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
