#!/usr/bin/env bash


prefix="registry_$2"


executionplane --silent docker container prune --force

if [[ "registry_local_metrics_monitor_heartbeat_data_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "registry_local_metrics_monitor_heartbeat_data_volume"
			result=$(docker volume ls | grep "registry_local_metrics_monitor_heartbeat_data_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "registry_local_metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "registry_local_metrics_monitor_heartbeat_monitors_volume"
			result=$(docker volume ls | grep "registry_local_metrics_monitor_heartbeat_monitors_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "registry_local_registry_registry_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "registry_local_registry_registry_volume"
			result=$(docker volume ls | grep "registry_local_registry_registry_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
