#!/usr/bin/env bash


prefix="registry_$2"

if [[ "registry_local_metrics_monitor_heartbeat_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create registry_local_metrics_monitor_heartbeat_data_volume
	fi
	
if [[ "registry_local_metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create registry_local_metrics_monitor_heartbeat_monitors_volume
	fi
	
if [[ "registry_local_registry_registry_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create registry_local_registry_registry_volume
	fi
	
if [[ "registry_local_metrics_monitor_heartbeat_monitors_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v registry_local_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /modeco/volumes/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		fi
		
