#!/usr/bin/env bash



executionplane --silent docker container prune --force

continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "registry_local__registry_volume"
	result=$(docker volume ls | grep "registry_local__registry_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
