#!/usr/bin/env bash

##### START COMPONENT CONFIGURATION #####
export SOLECO_MODULE="package.registry"
export SOLECO_MODULE_VERSION=""
export SOLECO_NETWORKLOCAL_PARENT="true"
##### START COMPONENT CONFIGURATION #####
