
- type: tcp
  id: internal_kz_kafka
  name: KZ Kafka Internal
  hosts: ["package_metrics_monitor_kz_kafka"]
  ports: [9092]
#  check.send: 'Hello World'
#  check.receive: 'Hello World'
  schedule: '@every 30s'
  fields:
    scope: "package_metrics_monitor"
    stack: kz
    type: internal
    service: ksql_server
    area: endpoint

- type: tcp
  id: internal_kz_zookeeper
  name: KZ Zookeeper Internal
  hosts: ["package_metrics_monitor_kz_zookeeper"]
  ports: [2181]
#  check.send: 'Hello World'
#  check.receive: 'Hello World'
  schedule: '@every 30s'
  fields:
    scope: "package_metrics_monitor"
    stack: kz
    type: internal
    service: ksql_server
    area: endpoint
