- type: http
  id: external_registry_endpoint
  name: External Registry Endpoint
  hosts: ["http://${MODECO_HOSTNAME}:${MODECO_REGISTRY_REGISTRY_ENDPOINT_PORT}"]
  check.response.status: [200]
  schedule: '@every 30s'
  fields:
    scope: module
    stack: registry
    type: external
    service: registry
    area: endpoint
