#!/usr/bin/env bash

##### START MOULE CONFIGURATION KEYVALUES #####
##### END MOULE CONFIGURATION KEYVALUES #####
#!/usr/bin/env bash

##### START COMPONENT CONFIGURATION #####
export SOLECO_MODULE="package.metrics_monitor"
export SOLECO_MODULE_VERSION=""
export SOLECO_HIDE_COMPONENT="true"
##### END COMPONENT CONFIGURATION #####
