#!/usr/bin/env bash


	executionplane --silent docker volume create registry_local_metrics_monitor_metrics_monitor_heartbeat_data_volume
	
	executionplane --silent docker volume create registry_local_metrics_monitor_metrics_monitor_heartbeat_monitors_volume
	
executionplane --silent docker run -v registry_local_metrics_monitor_metrics_monitor_heartbeat_monitors_volume:/usr/share/heartbeat/monitors.d ${CONTECO_REGISTRY}$1 --interactive cp -r /soleco/metrics_monitor/_component/_volumes/metrics_monitor_heartbeat_monitors_volume/* /usr/share/heartbeat/monitors.d
		
