#!/usr/bin/env bash


prefix="registry_$2"


executionplane --silent docker container prune --force

continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "solution_registry_local_metrics_monitor_heartbeat_data_volume"
	result=$(docker volume ls | grep "solution_registry_local_metrics_monitor_heartbeat_data_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;

continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "solution_registry_local_metrics_monitor_heartbeat_monitors_volume"
	result=$(docker volume ls | grep "solution_registry_local_metrics_monitor_heartbeat_monitors_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;

continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "solution_registry_local_registry_registry_volume"
	result=$(docker volume ls | grep "solution_registry_local_registry_registry_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
